site_name: 锦鲤部署
site_description: 锦鲤容器管理部署工具是致力于解决中小站长部署环境问题，主打“性能调优”、“内核级别php安全组件”。
theme:
  name: null
  custom_dir: material
  palette:
    # scheme: slate
    # primary: blue grey
    # accent: yellow
  font: false
  language: zh
  icon:
    logo: logo
  favicon: images/favicon.png
  features:
    tabs: true
repo_url: https://github.com/jinlicode/jinliconfig
# plugins:
#   - git-revision-date
nav:
  - 首页: index.md
  - 产品文档:
      - 产品优势: docs/advantage.md
      - 服务器要求: docs/service.md
      - 常用工具下载: docs/tools.md
      - 开始使用: docs/getting-started.md
      - 创建第一个网站: docs/create_first_website.md
      - 常用linux命令: docs/cmd.md
      - php版本说明: docs/php_ver.md
      - 视频教程: docs/video.md
      - 目录结构: docs/directory.md
      - 服务器安全加固: docs/server_steady.md
      - 常见问题: docs/FAQ.md
      - bug报告: docs/bug_issue.md
      - 许可协议: docs/license.md
  - 开发:
      - 开发规范: development/specification.md
      - 贡献代码: development/pull_requests.md
      - 许可协议: development/license.md
  - 更新日志:
      - 更新日志: update/upgrading.md
      - 放弃内容: update/deprecations.md
